---
infra_fdt_groups2create_p2p_entry:
  - name: raven
    gid: 1111
infra_fdt_users2create_p2p_entry:
  - name: raven
    uid: 1111
    groups: wheel

grafana_url: "https://{{ ansible_fqdn }}/grafana/"
prometheus_web_external_url: "https://{{ ansible_fqdn }}/prometheus/"
grafana_server:
  serve_from_sub_path: true

infra_fdt_content2upload_p2p_entry:
  - dest: /etc/nginx/htaccess-admin
    mode: "0644"
    force: "yes"
    follow: "no"
    content: |
      # login: 'c39to62mMPbCLz', password: 'fTyEv1rc5Ym7kFt'
      c39to62mMPbCLz:$apr1$GyI8RwlY$BgYYeJK3ZeZZw1rCIov1g/

nginx_location_basic_auth:
  auth_basic: restricted area
  auth_basic_user_file: /etc/nginx/htaccess-admin

nginx_location_grafana:
  location: /grafana
  proxy_pass: http://127.0.0.1:3000
  proxy_redirect: http://127.0.0.1:3000/ $xscheme://$host/

nginx_location_prometheus:
  location: /prometheus
  proxy_pass: http://127.0.0.1:9090
  proxy_redirect: http://127.0.0.1:9090/ $xscheme://$host/

nginx_config_http_templates_p2p_entry:
  default:
    servers:
      default_http:
        web_server:
          locations:
            main: >
              {{ nginx_location_redirect2https |
              combine(
                nginx_location_defaults_all,
                recursive = True,
                list_merge = 'append',
              ) }}
      p2p_entry_https:
        server_name: >-
          p2p-test
          p2p-entry.o6a.ru
        listen: "{{ nginx_https_listen }}"
        reverse_proxy:
          locations:
            grafana: >
              {{ nginx_location_proxy_all |
              combine(
                nginx_location_grafana,
                recursive = True,
                list_merge = 'append',
              ) |
              combine(
                nginx_location_basic_auth,
                recursive = True,
                list_merge = 'append',
              ) }}
            prometheus: >
              {{ nginx_location_proxy_all |
              combine(
                nginx_location_prometheus,
                recursive = True,
                list_merge = 'append',
              ) |
              combine(
                nginx_location_basic_auth,
                recursive = True,
                list_merge = 'append',
              ) }}
