---
prometheus_version: "2.22.1"
prometheus_web_external_url: "http://{{ ansible_hostname }}:9090"
prometheus_storage_retention: "0"
prometheus_db_dir: "/prom"
# storage should be mounted to /prom
prometheus_storage_retention_size: >-
  {{
    (
      (
        ansible_mounts |
        selectattr(
          'mount',
          'in',
          prometheus_db_dir
        ) | list | sort(
          attribute='mount'
        )
      )[-1]['size_total'] * 0.5 / 1048576 - 999
    ) | int
  }}MB
prometheus_global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 30s
prometheus_alert_rules:
  - alert: watchdog
    expr: vector(1)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "{% raw %}prometheus AlertManager E2E dead man switch{% endraw %}"
      description: "{% raw %}Prometheus DeadManSwitch is an always-firing alert. It's used as an end-to-end test of Prometheus through the Alertmanager.{% endraw %}"
prometheus_targets: "{{ groups | inv2ptrgt(hostvars) }}"
prometheus_scrape_configs: "{{ groups | inv2scrape(hostvars) }}"
