{
 "title": "gaiad totals v1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "i",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DASOU", "label": "DS", "query": "prometheus" },
   { "name": "nick", "query": "label_values(up, nick)" }
  ]
 },
 "panels": [
  { "title": "Recent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lag of latest block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(gaiad_latest_block_time{nick=~\"$nick\"})-gaiad_latest_block_time{nick=~\"$nick\"}",
     "legendFormat": "gaiad latest block late"
    }
   ]
  },
  {
   "title": "Latest block number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_count{nick=~\"$nick\"}",
     "legendFormat": "Latest block number"
    }
   ]
  },
  {
   "title": "Amount of peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tendermint_p2p_peer_send_bytes_total{nick=~\"$nick\"})",
     "legendFormat": "Latest block number"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Block time",
   "type": "graph",
   "description": "[$interval] Latest block time lag (left) and calculating speed in seconds per real second (right)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "yaxes": [
    { "format": "dtdhms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gaiad_latest_block_time{nick=~\"$nick\"}[$__rate_interval]))",
     "legendFormat": "Speed in seconds"
    },
    {
     "expr": "sum(timestamp(gaiad_latest_block_time{nick=~\"$nick\"})-gaiad_latest_block_time{nick=~\"$nick\"})",
     "legendFormat": "Lag total"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "description": "[$interval] Total blocks amount (left) and calculating speed in blocks per second (right)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tendermint_state_block_processing_time_count{nick=~\"$nick\"}[$__rate_interval]))",
     "legendFormat": "Blocks per second"
    },
    {
     "expr": "sum(tendermint_state_block_processing_time_count{nick=~\"$nick\"})",
     "legendFormat": "Total blocks"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "[$interval] Amount of peers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(tendermint_p2p_peer_send_bytes_total{nick=~\"$nick\"})",
     "legendFormat": "Peers"
    }
   ]
  }
 ]
}