{
 "title": "Node Exporter Totals",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "i",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DASOU", "label": "DS", "query": "prometheus" },
   { "name": "job", "query": "label_values(up, job)" },
   {
    "name": "cluster",
    "query": "label_values(up{job=~\"$job\"}, cluster)"
   },
   { "name": "filter", "query": ".+" },
   {
    "name": "nick",
    "query": "label_values(up{job=~\"$job\",cluster=~\"$cluster\",nick=~\"$filter\"}, nick)"
   },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"$job\",cluster=~\"$cluster\",nick=~\"$nick\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Recent stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "bargauge",
   "description": "Summary of CPU recent usage for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n count(\r\n  count(\r\n   node_cpu_seconds_total{instance=~\"$instance\"}\n  ) by (cpu, instance)\r\n ) - sum(\r\n  irate(\r\n   node_cpu_seconds_total{mode='idle',instance=~\"$instance\"}\r[$__rate_interval]\n  )\r\n )\r\n) * 100\r\n",
     "legendFormat": "Used"
    },
    {
     "expr": " count(\r\n  count(\r\n   node_cpu_seconds_total{instance=~\"$instance\"}\n  ) by (cpu, instance)\r\n ) * 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "description": "Summary of RAM recent usage for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_MemFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_SwapFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "bargauge",
   "description": "Summary of load averages recent usage for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$instance\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum(node_load5{instance=~\"$instance\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum(node_load15{instance=~\"$instance\"})",
     "legendFormat": "15m"
    },
    {
     "expr": "count(\r\n count(\r\n  node_cpu_seconds_total{instance=~\"$instance\"}\n ) by (cpu, instance)\r\n)",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "bargauge",
   "description": "Summary of the network traffic recent usage for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Root FS",
   "type": "bargauge",
   "description": "Summary of RootFS recent usage for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime for selected nodes together",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_time_seconds{instance=~\"$instance\"}) - sum(node_boot_time_seconds{instance=~\"$instance\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Basic stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "description": "[$interval] Summary of CPU usage for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Interrupts"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "IOwait"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "System"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "User"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"nice\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Nice"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"steal\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Steal"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|user|system|iowait|.*irq|steal|nice\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Other"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "description": "[$interval] Summary of RAM usage for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_MemFree_bytes{instance=~\"$instance\"}) - (sum(node_memory_Cached_bytes{instance=~\"$instance\"}) + sum(node_memory_Buffers_bytes{instance=~\"$instance\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(node_memory_Cached_bytes{instance=~\"$instance\"})"
      },
      {
       "expr": "sum(node_memory_Buffers_bytes{instance=~\"$instance\"})",
       "legendFormat": "Buffers"
      },
      {
       "expr": "sum(node_memory_MemFree_bytes{instance=~\"$instance\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_SwapFree_bytes{instance=~\"$instance\"})",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Load averages",
     "type": "graph",
     "description": "[$interval] Summary of load averages for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(node_load15{instance=~\"$instance\"})",
       "legendFormat": "15 min"
      },
      {
       "expr": "sum(node_load5{instance=~\"$instance\"})",
       "legendFormat": "5 min"
      },
      {
       "expr": "sum(node_load1{instance=~\"$instance\"})",
       "legendFormat": "1 min"
      },
      {
       "expr": "sum(node_load1{instance=~\"$instance\"}) + sum(node_load5{instance=~\"$instance\"}) + sum(node_load15{instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "description": "[$interval] Summary of uptime for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "yaxes": [
      { "format": "dtdhms" }
     ],
     "targets": [
      {
       "expr": "sum(node_time_seconds{instance=~\"$instance\"}) - sum(node_boot_time_seconds{instance=~\"$instance\"})",
       "legendFormat": "Uptime"
      }
     ]
    }
   ]
  },
  {
   "title": "Network stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "description": "[$interval] Summary of the network traffic for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))*8",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))*8",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "graph",
     "description": "[$interval] Summary of the network packets for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Network multicast",
     "type": "graph",
     "description": "[$interval] Summary of the network multicast for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_multicast_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Network issues",
     "type": "graph",
     "description": "[$interval] Summary of the network issues for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Drop received"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Drop transmit"
      },
      {
       "expr": "sum(irate(node_network_receive_errs_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Errors received"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{device!~\"one.+|vlan.+|br.+|lo|bond.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Errors transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RootFS",
     "type": "graph",
     "description": "[$interval] Summary of RootFS usage for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Avail"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Disk busy",
     "type": "graph",
     "description": "[$interval] Summary of the disks busy in seconds for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_io_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Busy time"
      },
      {
       "expr": "count(irate(node_disk_io_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval])) - sum(irate(node_disk_io_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Free time"
      },
      {
       "expr": "count(irate(node_disk_io_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Total time"
      }
     ]
    },
    {
     "title": "Filesystem issues",
     "type": "graph",
     "description": "[$interval] Summary of the filesystem issues for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$instance\",device!~'rootfs'} > 0",
       "legendFormat": "{{instance}}:{{mountpoint}} - r/o"
      },
      {
       "expr": "node_filesystem_device_error{instance=~\"$instance\",fstype!~'tmpfs|rootfs',mountpoint!~'.+ceph/osd.+'} > 0",
       "legendFormat": "{{instance}}:{{mountpoint}} - device error"
      }
     ]
    },
    {
     "title": "Disk time",
     "type": "graph",
     "description": "[$interval] Summary of the completed disk seconds for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Read seconds"
      },
      {
       "expr": "sum(irate(node_disk_read_time_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Write seconds"
      },
      {
       "expr": "sum(irate(node_disk_io_time_weighted_seconds_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Weight seconds"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "description": "[$interval] Summary of the completed disk IOPS for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_reads_completed_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Read IOPS"
      },
      {
       "expr": "sum(irate(node_disk_writes_completed_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Write IOPS"
      }
     ]
    },
    {
     "title": "Disk bytes",
     "type": "graph",
     "description": "[$interval] Summary of the completed disk bytes for selected nodes together",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Read bytes"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total{device=~\"sd.+|vd.+|nvme.+\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Write bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardware critical temperature monitor",
     "type": "graph",
     "description": "[$interval] Summary of the hardware critical temperature for selected nodes together",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=~\"$instance\"} > node_hwmon_temp_crit_celsius{instance=~\"$instance\"} - 15",
       "legendFormat": "{{nick}} {{instance}} {{chip}} {{sensor}} temp"
      }
     ]
    },
    {
     "title": "Throttle cooling device",
     "type": "graph",
     "description": "[$interval] Summary of the hardware throttle for selected nodes together",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_cooling_device_cur_state{instance=~\"$instance\"} > 0",
       "legendFormat": "{{nick}} {{ instance }} current {{ name }} in {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}