---
all:
  vars:
    infra_base_selinux_state: enforcing
    plabel_env: urgent
    plabel_team: infra
install_safe_base:
  children:
    p2p_entry:
main:
  children:
    p2p_entry:
file_dir_tpl:
  children:
    p2p_entry:
p2p_entry:
  hosts:
    p2p-test:
      ansible_host: p2p-test.local
ptrgt_prom_exporter:
  vars:
    prom_exporter:
      plabel_cluster: prom
      scrape_port: 9090
      scrape_config:
        metrics_path: /prometheus/metrics
  children:
    prometheus:
ptrgt_node_exporter:
  vars:
    node_exporter:
      plabel_cluster: node-any
      scrape_port: 9100
      scrape_config:
        basic_auth:
          username: c39to62mMPbCLz
          password: fTyEv1rc5Ym7kFt
  children:
    p2p_entry:
prometheus:
  children:
    p2p_entry:
metric_exporters:
  children:
    p2p_entry:
