---
- name: empty play to getting facts
  hosts: install_safe_base
  remote_user: root
  tags: [always]

- name: safe part of base config to non-IaC nodes
  hosts: install_safe_base
  remote_user: root
  handlers:
    - import_tasks: handlers/main.yaml
  roles:
    - infra/base-main-safe
  tags: [infra-base-safe]

- name: apply common configuration to IaC nodes
  hosts: main
  remote_user: root
  handlers:
    - import_tasks: handlers/main.yaml
  roles:
    - infra/base-selinux
    - infra/base-main-full
  tags: [infra-base-full]

- name: perform some files, dirs, and templates upload
  hosts: file_dir_tpl
  remote_user: root
  handlers:
    - import_tasks: handlers/main.yaml
  roles:
    - infra/file-dir-tpl
  tags: [file-dir-tpl]
